<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      /*
      1. Promise 생성 및 활용 방법
      */
      // 기본 Promise 함수 생성
      // 생성자의 인자로 넘어가는 함수 인자의 바디에서는 resolve()나 reject() 함수를 정상 처리,
      // 예외 발생 여부에 따라 적절히 호출해줘야 한다.
      // 일반적으로 resolve() 함수의 인자로는 미래 시점에 얻게될 결과를 넘겨주고,
      // reject() 함수의 인자로는 미래 시점에 발생할 예외를 넘겨준다.

      // function returnPromise() {
      //   return new Promise((resolve, reject) => { ... } );
      // }

      // 예제
      function divide(numA, numB) {
        return new Promise((resolve, reject) => {
          if (numB === 0) reject(new Error("Unable to divide by 0."));
          else resolve(numA / numB);
        });
      }

      divide(8, 2) // divide(8, 0) 으로 변경하면 오류가 발생된다.
        .then((result) => console.log("성공:", result))
        .catch((error) => console.log("실패:", error));

      // 보통은 위와 같이 Promise를 직접 생성해서 리턴해주는 코드 보다는
      // 어떤 라이브러리의 함수를 호출해서 리턴 받은 Promise 객체를 사용하는 경우가 더 많다.
      // 대표적인게 fetch() 함수이다. fetch() 함수는 Promise 객체를 리턴한다.
      // Promise 객체의 then() 메소드는 결과값을 가지고 수행할 로직을 담은 콜백 함수를 인자로 받는다.
      // 그리고 catch() 메서드는 예외 처리 로직을 담은 콜백 함수를 인자로 받는다.
      // then()과 catch() 메서드를 통해서 동기 처리 코드에서 사용하던
      // try-catch 블록과 유사한 방법으로 비동기 처리 코드를 작성할 수 있도록 해준다.

      fetch("https://jsonplaceholder.typicode.com/posts/1")
        .then((response) => console.log("response:", response))
        .catch((error) => console.log("error:", error));

      // then()과 catch() 메서드는 또 다른 Promise 객체를 리턴한다.
      // 그리고 이 Promise 객체는 인자로 넘긴 콜백 함수의 리턴값을 다시
      // then()과 catch() 메서드를 통해 접근할 수 있도록 해줍니다.
      // 다시 말하면 then()과 catch() 메서드는 마치 사슬처럼 계속 연결하여 연쇄적으로 호출을 할 수 있으며
      // 이를 메서드 체이닝(method chaining) 이라고 한다.

      // response는 HTTP 응답 전체를 나타내는 객체로,
      // JSON 본문 콘텐츠를 추출하기 위해서는 json() 메서드를 호출해야 한다.
      fetch("https://jsonplaceholder.typicode.com/posts/1")
        .then((response) => response.json())
        .then((post) => console.log("post:", post))
        .catch((error) => console.log("error:", error));

      // 또 다른 메서드 체이닝 예제
      function fetchAuthorName(postId) {
        return fetch(`https://jsonplaceholder.typicode.com/posts/${postId}`)
          .then((response) => response.json())
          .then((post) => post.userId)
          .then((userId) => {
            return fetch(`https://jsonplaceholder.typicode.com/users/${userId}`)
              .then((response) => response.json())
              .then((user) => user.name);
          });
      }

      fetchAuthorName(1).then((name) => console.log("name:", name));

      // 위 메서드 체이닝 스타일 코드의 문제점은 오류 발생 시
      // 동일한 이름의 메서드인 then()을 연쇄적으로 호출하고 있어서
      // 도대체 몇 번째 then()에서 문제가 발생한 건지 Stack Trace을 보더라도 혼란스러울 수 있다.

      // 또한 Promise를 사용하면 try/catch 대신에 catch() 메서드를 사용하여 예외 처리를 해야한다.
      // 이 부분이 비동기 코드만 있을 때는 그렇게 거슬리지 않는데,
      // 동기 코드와 비동기 코드가 섞여 있을 경우 예외 처리가 난해해지거나 예외 처리를 누락하는 경우가 생기기 쉽다.

      // 최근에는 이러한 Promise를 이용해서 계속해서 메서드 체이닝하는
      // 코딩 스타일은 자바스크립트의 async/await 키워드를 사용하는 방식으로 대체할 수 있다.

      /*
      async/await 키워드를 통한 비동기 처리
      Promise의 이러한 불편한 점들을 해결하기 위해 ES7(ES2017)에서 async/await 키워드가 추가

      async 키워드가 function 앞에 붙는다.
      Promise를 리턴하는 모든 비동기 함수 호출부 앞에는 await 키워드를 추가해준다.
      
      await 키워드는 async 키워드가 붙어있는 함수 내부에서만 사용 가능.
      await 키워드를 사용하면 일반 비동기 처리처럼 바로 실행이 다음 라인으로 넘어가는 것이 아니라
      결과값을 얻을 수 있을 때까지 기다려준다.
      
      따라서 일반적인 동기 코드 처리와 동일한 흐름으로(함수 호출 후 결과값을 변수에 할당하는 식으로)
      코드를 작성할 수 있으며, 따라서 코드를 읽기도 한결 수월해진다.

      주의할 점은 async 키워드가 붙어있는 함수를 호출하면 명시적으로 Promise 객체를
      생성하여 리턴하지 않아도 Promise 객체가 리턴된니다.
      따라서 호출부를 보면 Promise 객체를 사용했던 것과 동일한 방식으로
      then() 메서드를 통해서 결과값을 출력하고 있다.
      */
      async function fetchAuthorName(postId) {
        const postResponse = await fetch(
          `https://jsonplaceholder.typicode.com/posts/${postId}`
        );
        const post = await postResponse.json();
        const userId = post.userId;
        const userResponse = await fetch(
          `https://jsonplaceholder.typicode.com/users/${userId}`
        );
        const user = await userResponse.json();
        return user.name;
      }

      fetchAuthorName(1).then((name) => console.log("name:", name));

      // 동기/비동기 구분없이 try/catch로 일관되게 예외 처리 가능
      async function fetchAuthorName(postId) {
        const postResponse = await fetch(
          `https://jsonplaceholder.typicode.com/posts/${postId}`
        );
        const post = await postResponse.json();
        const userId = post.userId;

        try {
          const userResponse = await fetch(
            `https://jsonplaceholder.typicode.com/users/${userId}`
          );
          const user = await userResponse.json();
          return user.name;
        } catch (err) {
          console.log("Fail to fetch user:", err);
          return "Unknown";
        }
      }

      fetchAuthorName(1).then((name) => console.log("name:", name));
    </script>
  </body>
</html>
